### ISSUE TITLE
Meeting Notes Update [Mon, 5 Nov, 2018] 

### ISSUE THREAD

**Issue by ozgedincsoy** [bounswe/bounswe2018group3#119]
There are missing parts in meeting notes of this semesters. You can take [https://github.com/bounswe/bounswe2018group3/wiki/Meeting-%236](the last meeting note) as a template. The first 5 note should be reviewed.

**Comment by cagdastombul** [comment]
Meeting Note 6 is updated.

**Comment by cagdastombul** [comment]
Meeting Note 5 is updated but not finished yet. I need the people below to inform me, considering the date, about what they did exactly to be able to update the TODOs.
- @ozgedincsoy 
- @unstablecursor 
- @pxfurkanenes 
- @OmegaIV 
- @oguzhanyetimoglu
