### ISSUE TITLE
Web Annotation Data Model

### ISSUE THREAD

**Issue by pxfurkanenes** [bounswe/bounswe2018group3#147]
After reading Web Annotation Data Model, we noticed that It would be better if we implement the model in a NoSQL Database. Then we taught, since we didn't implement too many models, we can change our existing SQL Database to a NoSQL Database, MongoDB.

We, backend team, tried to migrate to MongoDB but it was a disaster. We couldn't manage to migrate without losing significant amount of functionality. Hence, we decided to stick with SQL for our website models.

We decided to use a new design for implementing Annotations. We will continue to use our existing database for everything except Annotations. When a request arrives at an Annotation related endpoint, we will try to connect another database which will be a MongoDb.

If anybody has a better idea or an objection, s/he can write it here.

**Comment by OmegaIV** [comment]
We decided to continue using SQLite for annotations, as switching to NoSQL was not necessary after all.
