### ISSUE TITLE
Send Drive documents for Documentation of Requirements file. [Monday, 12 Feb, 23.59]

### ISSUE THREAD

**Issue by unstablecursor** [bounswe/bounswe2018group3#16]

**Comment by ozgedincsoy** [comment]
Non functional
https://docs.google.com/document/d/1zXh7HyDTPo8hPte-K1I9onPSGgeqnAa6oHZCoallf8w/edit?usp=sharing

functional

https://docs.google.com/document/d/1esoniNmPdsYe9Th5ej7tPoTBaBoRKujEOPKz_TCmRrg/edit?usp=sharing

user

https://docs.google.com/document/d/12r9C1g5twu2myb1TLsNDjUplwdC-TUKnI1fjss_TV2Y/edit?usp=sharing

**Comment by unstablecursor** [comment]
Everybody filled the draft files.
