### ISSUE TITLE
Tags on Simple Event List on the Homepage

### ISSUE THREAD

**Issue by cagdastombul** [bounswe/bounswe2018group3#210]
Tags should be shown on the Homepage in the simple event list.

**Comment by mustafasisik** [comment]
Tags listed in simple event as recyclerview, and set it onclicklistener for searching new events by that tag.

**Comment by mustafasisik** [comment]
It is ready after tags are able to get from backend.

**Comment by cagdastombul** [comment]
Tags are available on the homepage. They are shown when an event has tags.
