### ISSUE TITLE
Documentation of backend end points

### ISSUE THREAD

**Issue by ugurcanarikan** [bounswe/bounswe2018group3#226]
We need an up to date documentation of the backend endpoints clearly showing their purpose and correct way to use them with method type ( such as post, get etc.) and necessary parameters/headers etc.

**Comment by OmegaIV** [comment]
Documentation is already written and updated. You can find it in wiki (on sidebar)

**Comment by OmegaIV** [comment]
https://github.com/bounswe/bounswe2018group3/wiki/Documentation-for-Available-Backend-Endpoints
