### ISSUE TITLE
Field Difference in Events and Event Search

### ISSUE THREAD

**Issue by cagdastombul** [bounswe/bounswe2018group3#227]
When retrieving events from http://139.59.128.92:8080/api/v1/events/ and from http://139.59.128.92:8080/api/v1/events/search/?search=, some fields seem different like rating.

**Comment by OmegaIV** [comment]
I am working on this right now, it will be fixed by tomorrow

**Comment by OmegaIV** [comment]
Rating fields from search should be coming normally now
