### ISSUE TITLE
Requirements [Friday, 16 Feb, 23.59]

### ISSUE THREAD

**Issue by ozgedincsoy** [bounswe/bounswe2018group3#23]
Does everyone complete his/her requirement part? It should be prepare until this friday because we should transfer drive documents here in an appropriate way in the weekend.

- [x] @unstablecursor 
- [ ] @uvut 
- [x] @ali-uslu 
- [x] @anilcankara 
- [x] @emreboun 
- [x] @oguzhanyetimoglu 
- [x] @OmegaIV 
- [x] @pxfurkanenes

**Comment by unstablecursor** [comment]
Page is ready
