### ISSUE TITLE
Communication mail

### ISSUE THREAD

**Issue by oguzhanyetimoglu** [bounswe/bounswe2018group3#3]
Can you write your mail adresses here?

**Comment by ozgedincsoy** [comment]
ozgedincsoyboun@gmail.com

**Comment by pxfurkanenes** [comment]
furkanyaln9@gmail.com

**Comment by unstablecursor** [comment]
recepdeniza@gmail.com

**Comment by anilcankara** [comment]
anil.cn.kr@gmail.com

**Comment by emreboun** [comment]
abdurrahmanemreyilmaz@gmail.com

**Comment by ali-uslu** [comment]
ali.uslu@boun.edu.tr

**Comment by OmegaIV** [comment]
onur.varkivanc@boun.edu.tr
