### ISSUE TITLE
Project Plan Research

### ISSUE THREAD

**Issue by ozgedincsoy** [bounswe/bounswe2018group3#32]
I think, we can use [canva](https://www.canva.com/graphs/gantt-charts/) to create gantt chart. It provides various gantt chart templates for us.

**Comment by ozgedincsoy** [comment]
Also, we should decide on titles of the project plan.

**Comment by unstablecursor** [comment]
HW3 file has been updated, apparently we should use https://www.projectlibre.com/ for Gantt chart.

**Comment by unstablecursor** [comment]
Revision of the chart is done.
