### ISSUE TITLE
Designing mockups: Finding a tool [28 Feb, 23:59]

### ISSUE THREAD

**Issue by unstablecursor** [bounswe/bounswe2018group3#35]
I've found one: http://pencil.evolus.vn/

We can find other open source mockup tools.

**Comment by OmegaIV** [comment]
I don't know if this has been discussed but I think creating mockups using tools like Inkscape, Photoshop, etc. is also a choice. If we decide to take this approach I have some degree of experience with both programs which may come in handy.

**Comment by unstablecursor** [comment]
Thanks to god we finished it.
