### ISSUE TITLE
Web mockup event page revision

### ISSUE THREAD

**Issue by OmegaIV** [bounswe/bounswe2018group3#48]
>1.1.1.5 The system shall provide event price.

- [ ] Both Android and Web event page are missing price info

>1.2.1.7.7 Users shall be able to follow cultural events.

- [ ] Both Android and web event page don’t have a follow option.

> 1.1.1.7 The system shall provide rating and comments of the event.

- [x] Web page does not have a visible rating button.

**Comment by oguzhanyetimoglu** [comment]
Web page part is fixed.
