### ISSUE TITLE
Meeting for Class Diagrams[Tomorrow, 12 March, 17:30]

### ISSUE THREAD

**Issue by ozgedincsoy** [bounswe/bounswe2018group3#53]
Today, we decided to meet once or twice in this week, at Lounge. In the meetings, we will do our assignment by dividing it into parts. Whenever you are appropriate to come, you can participate us. I want to know who can come tomorrow and when so that we can prepare work plan. I will be there at 17:30.

**Comment by uvut** [comment]
> I will be there at 17:30.

+1

**Comment by pxfurkanenes** [comment]
> I will be there at 17:30

+1

**Comment by ali-uslu** [comment]
+1

**Comment by anilcankara** [comment]
Not specifically at 17.30, but I can be there around this time period.
