### ISSUE TITLE
Meeting Time

### ISSUE THREAD

**Issue by ozgedincsoy** [bounswe/bounswe2018group3#54]
Me and Anıl will organize these two weeks' meetings. Please inform us about your free time.

**Comment by uvut** [comment]
Mondays after 19:00
Wednesday after 16:00
Rest of the days are OK for me.

**Comment by anilcankara** [comment]
I am not available on Tuesday and Wednesday evenings. Any other option is OK with me.

**Comment by emreboun** [comment]
Friday after 17:00
Saturday after 17:00
Rest of the days are OK for me.
