### ISSUE TITLE
Creation of an Additional Box in the Homepage [Frontend]

### ISSUE THREAD

**Issue by anilcankara** [bounswe/bounswe2018group3#63]
Deniz, one of my functions posts a tweet specified by the user. It takes an argument called "YourTweet" which represents the string that the user enters to tweet. Can you create an additional box for that purpose in our homepage, like val1 and val2?

**Comment by unstablecursor** [comment]
Anil, btw you can easily manipulate HTML if you look up on w3 guide on internet. 
https://www.w3schools.com/html/
