### ISSUE TITLE
Detailed project description file link is broken -- should be a wiki page

### ISSUE THREAD

**Issue by uskudarli** [bounswe/bounswe2018group3#69]
the detailed project description link in your main Wiki page is broken: https://github.com/bounswe/bounswe2018group3/blob/master/CulturalActivitiesProjectDescription.pdf.

The wiki needs to be fixed and description should be a wiki document (not pdf)

(Note: I added a requirements tag for this. If you want it remove "temp". Else, find something appropriate that works for such issues) Also, I created a milestone, as you had none.

**Comment by oguzhanyetimoglu** [comment]
The wiki fixed and description added to wiki.
