### ISSUE TITLE
Revise and Update The Requirements [Wed, 3 Oct, 19.00] 

### ISSUE THREAD

**Issue by cagdastombul** [bounswe/bounswe2018group3#72]
Revise and make suggestions about the requirements.

**Comment by cagdastombul** [comment]
As an additional requirement, we may add : 
-number of people attending to event

If it is okay, I will add it at 18.00, today. 

FYI

**Comment by ugurcanarikan** [comment]
Sounds good. Also, I have added "voting on comments" as a requirement.

**Comment by cagdastombul** [comment]
The following requirement is added:
1.2.1.7.9 Users shall be able to see how many people will attend or attended an event.
