### ISSUE TITLE
Revising Wiki For New Members

### ISSUE THREAD

**Issue by ozgedincsoy** [bounswe/bounswe2018group3#75]
In the right part of the wiki, there is a team members part. I added new team members names, please add your links there.

**Comment by ugurcanarikan** [comment]
Added my wiki page. Also updated homepage by replacing cmpe 352 with cmpe 451

**Comment by cagdastombul** [comment]
My wiki page is linked and ready.

**Comment by mustafasisik** [comment]
I have added my wiki page link.
