### ISSUE TITLE
Entering web pages from mobile phones

### ISSUE THREAD

**Issue by ozgedincsoy** [bounswe/bounswe2018group3#79]
Home page does not fit the screen when we enter the website from mobile. To avoid this, we can use Bootstrap library. Is it ok for you? Do you have any other suggestions?

**Comment by ugurcanarikan** [comment]
it is a good idea. we should use bootstrap.

**Comment by ugurcanarikan** [comment]
since we have decided to use material-ui instead, i am closing this.
