### ISSUE TITLE
Redesign frontend using material ui

### ISSUE THREAD

**Issue by ugurcanarikan** [bounswe/bounswe2018group3#85]
Redesigning sign in adn sign up pages using material-ui so that the pages will be responsive for the mobile as well.

**Comment by ugurcanarikan** [comment]
added new sign in, sign up and forgot password pages to the ua-frontend branch, though not connected with the backend and doesn't perform email check yet. also added a new logo and uninstalled semantic-ui-react dependency which we don't need anymore.
start command is the same.  
`npm install`
to install dependencies and then
`npm start`
inside robin folder.

**Comment by unstablecursor** [comment]
We decided to go with the bootstrap.
